USE [master]
GO

/****** Object:  Database [TPC1_BRITEZ]    Script Date: 09/25/2016 22:48:53 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'TPC1_BRITEZ')
DROP DATABASE [TPC1_BRITEZ]
GO

USE [master]
GO

/****** Object:  Database [TPC1_BRITEZ]    Script Date: 09/25/2016 22:48:53 ******/
CREATE DATABASE [TPC1_BRITEZ] ON  PRIMARY 
( NAME = N'TPC1_BRITEZ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TPC1_BRITEZ.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TPC1_BRITEZ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TPC1_BRITEZ_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TPC1_BRITEZ] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TPC1_BRITEZ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TPC1_BRITEZ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET ARITHABORT OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TPC1_BRITEZ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TPC1_BRITEZ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TPC1_BRITEZ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TPC1_BRITEZ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TPC1_BRITEZ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TPC1_BRITEZ] SET  READ_WRITE 
GO

ALTER DATABASE [TPC1_BRITEZ] SET RECOVERY FULL 
GO

ALTER DATABASE [TPC1_BRITEZ] SET  MULTI_USER 
GO

ALTER DATABASE [TPC1_BRITEZ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TPC1_BRITEZ] SET DB_CHAINING OFF 
GO

